from pathlib import Path
from datetime import datetime

# Paths
CATEGORIES_DIR = Path("categories")
STATUS_FILE = Path("STATUS.md")

today = datetime.utcnow().strftime("%Y-%m-%d")

total_entries = 0
category_counts = {}

# Count entries per category
for md in CATEGORIES_DIR.glob("*.md"):
    count = 0
    with md.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            if line.startswith("- "):
                count += 1

    category_name = md.stem.replace("-", " ").title()
    category_counts[category_name] = count
    total_entries += count

# Sort categories by count
sorted_categories = sorted(
    category_counts.items(), key=lambda x: x[1], reverse=True
)

# Build markdown table
category_table = "| Category | Total |\n|---------|------:|\n"
for name, count in sorted_categories:
    category_table += f"| {name} | {count} |\n"

status_content = f"""# 📊 Daily Security Writeups Status

**Date (UTC):** {today}

---

## 🔎 Summary
- Total writeups tracked: **{total_entries}**
- Categories tracked: **{len(category_counts)}**
- Automation status: ✅ Active

---

## 📂 Category Breakdown
{category_table}

---

## ⏱ Workflow Info
- Fetch workflow: Runs every few hours
- Status workflow: Runs daily at **23:55 UTC**

_Last updated automatically at end of day.  
Do not edit this file manually._
"""

STATUS_FILE.write_text(status_content, encoding="utf-8")

